### ISSUE TITLE
NoneTypeTypeError: expected string or bytes-like object, got 'NoneType'

### ISSUE THREAD

**Issue by thomergil** [JanWilczek/python-auto-tune#1]
$ python3 auto_tune.py --correction-method scale input.wav
Traceback (most recent call last):
  File "/Users/thomer/tmp/python-auto-tune/auto_tune.py", line 142, in <module>
    main()
  File "/Users/thomer/tmp/python-auto-tune/auto_tune.py", line 134, in main
    pitch_corrected_y = autotune(y, sr, correction_function, args.plot)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomer/tmp/python-auto-tune/auto_tune.py", line 86, in autotune
    corrected_f0 = correction_function(f0)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomer/tmp/python-auto-tune/auto_tune.py", line 61, in aclosest_pitch_from_scale
    sanitized_pitch[i] = closest_pitch_from_scale(f0[i], scale)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomer/tmp/python-auto-tune/auto_tune.py", line 42, in closest_pitch_from_scale
    degrees = degrees_from(scale)
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/thomer/tmp/python-auto-tune/auto_tune.py", line 19, in degrees_from
    degrees = librosa.key_to_degrees(scale)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/librosa/core/notation.py", line 692, in key_to_degrees
    match = KEY_RE.match(key)
            ^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by JanWilczek** [comment]
Please, specify the scale on the command line.

For details, run

```
python3 auto_tune.py --help
```

**Comment by thomergil** [comment]
My bad. But I suggest fixing the arg parsing to give a solid error message.

**Comment by JanWilczek** [comment]
This is not a production-ready program but a demo. But you can always provide a pull request if you want 🙂
Closing.
